### ISSUE TITLE
Amstrad CPC Mouse & Keyboard mapping

### ISSUE THREAD

**Issue by Julitium** [sorgelig/Amstrad_MiST#33]
Hi.
Mouse doesn't work for me.
I also haven't been able to mapping Right shift equal to Left shift.
I have edited the MiST.ini several times without any success. Please help.
The animated LED does not work either, but this is not important. I'm probably doing something wrong, but I don't know what.
Thank you very much for this core, it works great.
Greetings

**Comment by gyurco** [comment]
Right shift is mapped to \ currently. Maybe would be a better place for the backslash. Also the numeric keypad should be used for F-keys, too (as they are not function keys on the CPC, but a real numeric keypad).

**Comment by Julitium** [comment]
Hi Gyurco,
Thanks for responding, as always great support.
This is all very well, but it should be able to be remapped because there are other keys that are not used.
On the other hand, the mouse does not specify what type it implements (AMX, etc) and if it is through the usb port (like the other cores) or not.

I have not been able to map the right shift key or operate the usb mouse.

The rest of the Core is great and practically accurate.

Regards.

**Comment by gyurco** [comment]
From the README:
```
Kempston, SYMBiFACE II and Multiplay mice.
```
Just tried OCP Art Studio, Kempston works well.

**Comment by gyurco** [comment]
Btw, I think the intention to use the right shift as \ was to be able to play pinball games with the shift keys. (Macadam Bumper and the new Pinball Dreams works with this scheme).

**Comment by Julitium** [comment]
Solved!!!
Thanks.
