### ISSUE TITLE
Tape fail at Amstrad_20200704 update 

### ISSUE THREAD

**Issue by Julitium** [sorgelig/Amstrad_MiST#35]
Hi.
The latest version of the core amstrad (Amstrad_20200704) has been modified somewhat and there are already certain titles on tape that do not work (Rainbow island for example).
Testing in the previous version to this All work ok.
Regards.

**Comment by gyurco** [comment]
I've made a fix, Rainbow Island is OK now. Any other failing examples?

**Comment by Julitium** [comment]
Hi.
Rastan and target renegade also failed.
I test the fix and comment.
Regards

**Comment by Julitium** [comment]
Q. Where can I download the core from?
Thank you.

**Comment by gyurco** [comment]
Try this one:
https://github.com/gyurco/Amstrad_MiST/blob/master/releases/Amstrad_20200707.rbf

**Comment by Julitium** [comment]
Hi.
The Fix has not worked, now it puts garbage on the screen.
The right Shift / Backslash option is fine ... But right Ctrl doesn't work now. (important to make the shortcut for RUN "). It would also be very interesting to have the RESET option in the root menu.
Thank you very much Gyurco.

**Comment by gyurco** [comment]
I don't see any garbage. When does it happen to you? Please describe what you do, I don't want guessing.

**Comment by Julitium** [comment]
Hi.
I use 664 mode with a rom 6128/464 (maybe a memory management problem?) (fail in 6128 and 464).
The process is the usual loading for 464.
I charge the. CDT
I do a Ctrl + Enter (Ctrl + end) RUN ".
The problem appears before the loading screen (in Rastan and Target renegade it happens when loading is complete).
![IMG_20200708_005815](https://user-images.githubusercontent.com/20946038/86853154-43a9be00-c0b6-11ea-8fd9-b80b7bed3313.jpg)
Rainbow island in 464 mode (garbage). 
![IMG_20200708_005532](https://user-images.githubusercontent.com/20946038/86853211-5d4b0580-c0b6-11ea-80ff-7a2afac92108.jpg)
Rainbow island in 6128 mode (freeze here). 

Its works always on previous versions. 
Thank you.

**Comment by gyurco** [comment]
Is this happens with the official ROM?
https://github.com/sorgelig/Amstrad_MiST/blob/master/releases/amstrad.rom

**Comment by sorgelig** [comment]
It also happens on MiSTer. 
I didn't check sdram request but it seems new GA spams SDRAM, so no time left for tape.

**Comment by gyurco** [comment]
That would be strange, since the GA doesn't access the memory on its own.
Here's another attempt:
https://github.com/gyurco/Amstrad_MiST/blob/master/releases/Amstrad_20200708.rbf

**Comment by Julitium** [comment]
Hi.
The result is the same. Now there is no garbage on the screen.
There is one thing that I have noticed, the Led that indicates tape loading blinks, in the works version that is always on. I don't know if this means anything.

Regards

**Comment by gyurco** [comment]
That means I've added LED blinking for tape motor indicator, but it doesn't (or shouldn't) have any impact on the tape loading.

**Comment by gyurco** [comment]
Another attempt:
https://github.com/gyurco/Amstrad_MiST/blob/master/releases/Amstrad_20200710.rbf

**Comment by Julitium** [comment]
Hi.
The Fix does not work.
One thing that I have noticed is that when it reaches the critical point, the Load Led always stays on (I guess it is because of the freeze) maybe it is a clue.
Regards.

**Comment by Julitium** [comment]
Hi.
I have looked at the "Decapped" implementation of GA.
The only part that could apparently influence the tape is the IRQs. There is also a coincidence that the graphics to display could be Custom resolution (I'm not sure). The Blink of Led is very improbable that it is, consumes some type of resource? (ram, timer, irq, etc)?. 
I am not an expert, perhaps what I am saying is nonsense.
Regards.

**Comment by gyurco** [comment]
If the LED is constant ON, that means MF2 is activated. Hide it before loading protected programs (F11-r), it's expected to freeze with an active MF2 (as it's a copy-protection).

**Comment by Julitium** [comment]
Hi.
I have detected something curious. In the old core the tape load is frozen in Helichopper (Firebird). On new Core Helichopper loads well, must it be related to the New GA ?? .

Regards.

**Comment by Julitium** [comment]
Hi.
I have been testing all the software that gave problems with the previous core CPC.
Impressive !!!! .... Not only have the features been expanded and options added. Also the previous compatibility problems have been corrected !!!.
You are certainly a genius. You always surprise us reaching beyond what is expected.
I will continue testing the latest core.
If you like, I close this thread. Everything exposed is solved beyond what was expected.
Thank you very much Gyurco.

**Comment by Julitium** [comment]
Core Works fine. Thanks
